### PR TITLE
feat: Added button,empty,modal

### PR DESCRIPTION
**Pull request by gs-akhan**
Adding missing components

### CODE REVIEW

**Comment by gs-akhan** [comment]
@cipchk 
Also can you consider adding me contributor to this repo, I can work on adding all remaining attributes as well.

I use ngzorro very extensively and can help in improving this extension. 
Thanks

**Comment by gs-akhan** [comment]
@cipchk need a merge. :)

**Comment by cipchk** [comment]
Sorry, thanks for pr.

But I can’t merge him, because of these behaviors you can be very simple and intelligent, like this `nz-button`:

demo

**Comment by gs-akhan** [comment]
Hi, Thanks for the feedback.
Can you elaborate little more on whats wrong ? Because the button doesnt work with existing code.
Screenshot 2020-10-09 at 11 20 03 AM

**Comment by cipchk** [comment]
@gs-akhan Your upload fail of screenshots, pls check it.

**Comment by gs-akhan** [comment]
re uploaded.

**Comment by cipchk** [comment]
You can try to reinstall the extension, if it still, try to check if there is any error from the developer tool of vscode.

**Comment by gs-akhan** [comment]
Sure,
However can you please add modal to the extension or should I make another
PR for that.  ?

**Comment by gs-akhan** [comment]
@cipchk  please add modal, that will help us a lot .

**Comment by cipchk** [comment]
@gs-akhan If you want to make some code snippets for project, you can try this https://marketplace.visualstudio.com/items?itemName=cipchk.vscode-snippet-generator

**Pull request closed without merging**
